### PR TITLE
Django17

### PR DESCRIPTION
**Pull request by emord**
will test on staging

cc: @gcapalbo

### CODE REVIEW

**Comment by emord** [comment]
Deployed to staging and migrations did not freak out.

**Comment by gcapalbo** [comment]
:+1:

**Comment by gcapalbo** [comment]
(I think the merge is still pending @czue's comment about thinking through what else might go wrong and coming up with a rollout plan: https://github.com/dimagi/pillowtop/pull/120#issuecomment-123203411)

**Comment by emord** [comment]
@dannyroberts Ran these tests on HQ with django 1.6. Also been running on staging for 2 weeks. Should be good to go.

**Pull request merged**
